
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    # Config indicated by + and applies to all files under models/example/
    # Pour nettoyer la raw data avant de l'envoyer dans le wh
    stg:
      +materialized: view
      +description: "Nettoyage des données brutes"
      +profile: raw_dev
    wh:
      +materialized: table
      +description: "Pour stocker les données nettoyées"
      +profile: wh_dev
    int:
      +materialized: view
      +description: "Pour passer du wh au marts"
    marts:
      +materialized: table
      +description: "Pour les consommateurs"